### ISSUE TITLE
Windwos 11 64비트 환경에서 실행파일 실행이 안되는 문제점.

### ISSUE THREAD

**Issue by Tralala-hub** [BackGwa/Dokev_KrC#6]
메일로 보내드렸습니다만, 혹여 못보실까 여기에 남겨둡니다.

Net 7.0에 파이썬도 정상적으로 설치가 되어있는데, DoKev Runner를 실행하면 0.1초내지 사이에 떳다 사라지는 음,,,, 실행이 안되는 현상이 발생하는데. 어째서인지 알 수 있을까요?
구동 환경은 Windows 11 64비트 환경에서 진행했습니다.
백신 및, 방화벽관련 모든 옵션은 해제되어있구요, 마찬가지로 읽기 및 쓰기 권한도 정상적으로 부여되어있습니다.

**Comment by BackGwa** [comment]
DoKev가 실행이 안되는 부분에 관해서 아래 사항을 점검해주셨으면 합니다.

**1. 깃허브에서 릴리즈가 되어있는 버전 또는 브랜치 내 바이너리(bin)의 최신 엔진인가요?**
현재 최신 안정화 릴리즈는 `DoKev 7.01-rc` 버전이며 브랜치 릴리즈는 `DoKev 8 Pre-Release 4` 입니다.
한 번, 브랜치 릴리즈를 다운로드하고, 실행해주실 수 있을까요?

**2. `source.dkv` 파일이 있나요?**
`config.ini`에서 `[filename]` 내 `target`에 지정되어 있는 이름의 `dkv` 파일이 존재하지 않으면,
말씀하신 것처럼 컴파일러가 대상 파일을 찾지못하고 그대로 종료되게 됩니다.


**3. `.Net core`가 정상 설치되어 있는 환경인가요?**
원래 DoKev는 .Net core가 설치되어 있지 않으면, 아래와 같은 메세지가 출력됩니다.
`To run this application, you must install .Net Core.`

해당 메세지는 .Net Core가 설치되어 있지 않을 경우 출력이 되는 메세지입니다.
하지만, `트랄랄라`님께선 `.Net Core 7.0`이 설치되어 있는 상태라면,
정상적으로 `.Net Core`가 실행이 되고 있는지 확인이 필요해 보입니다.

아래 명령을 명령 프롬프트 혹은 Powershell에서 실행하여 정상적으로 설치가 되고 실행되는지 확인해주세요.

`dotnet --list-sdks`

**Comment by BackGwa** [comment]
추가적인 부분을 확인하였습니다.

DoKev가 일부 `.Net Core 7` 버전과 호환되지 않을 수 있습니다.
한 번 `.Net Core 6` 버전으로 실행을 해주실 수 있을까요?

**Comment by BackGwa** [comment]
방화벽 옵션 및 백신 옵션은 원래대로 복구하시길 바랍니다.
모두 비활성화한 상태라면, 컴퓨터의 보안이 매우 취약해질 수 있습니다.

**Comment by BackGwa** [comment]
.Net Core 6은 아래 링크에서 설치 할 수 있습니다.

https://dotnet.microsoft.com/ko-kr/download/dotnet/6.0

**Comment by Tralala-hub** [comment]
> 

말씀주신 내용들 전부 확인해보았습니다. net core, dkv 모두 정상적으로 있고 또 작동합니다. 8.0 pre 를 사용해보고 싶은데, 현재 릴리즈 업데이트를 보면 7.01-rc 기점으로 끊겨 있기에 다운로드가 불가합니다. 확인 가능할까요?

**Comment by Tralala-hub** [comment]
여전히 프로그램이 작동하지 않는데, 명확한 이유를 저도 모르겠네요. 8.0릴리즈 버전까지 확인해보고 여전히 문제점이 지속되면 한번 제가 다시 면밀히 볼 필요가 있을 것 같아요

**Comment by BackGwa** [comment]
main 브랜치 전체를 다운받으시면, bin 폴더 내에 8.0 pre 버전이 있습니다.

**Comment by BackGwa** [comment]
한 번 명령프롬프트에 실행 파일을 드래그해서 나오는 결과를 볼 수 있을까요?

**Comment by Tralala-hub** [comment]
헉. 8.0으로 하니까 바로 해결되었네요

**Comment by Tralala-hub** [comment]
감사합니다!

**Comment by Tralala-hub** [comment]
정말, 대단하십니다. 이 많은걸 한국어로 소화하기가 정말 쉽지 않은 일인데;;; 이것을 시발점으로 한글코딩도 많이 알려져서 실용적으로 어린아이들도 무리없이 접근할 수 있게끔 접근성이 더 용이하게끔 퍼졌으면 좋겠네요. 엔트리 스크래치같은 블록코딩들도 좋지만, 우리가 기본적으로 하는 python이나 C와는 방식에 거리감이 있다는 생각이 들었어서. 너무 좋은 프로젝트인것 같습니다. 항상 화이팅입니다.

**Comment by BackGwa** [comment]
DoKev 프로젝트에 큰 관심을 가져주셔서 정말로 감사드립니다!
